spring:
  application:
    name: ast

  profiles:
    group:
      local: openapi
      prod: openapi
      beta: openapi
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

logging:
  config: classpath:log4j2/log4j2-${spring.profiles.active}.xml

notify:
  discord-webhook:
    url: https://discord.com/api/webhooks/1200783808279101572/58SyrsR6ZnWmbPCBDll6ONWAqY7AMZIV15V5L3g2Grb_KQtNkkJrZSaTuNqOBWLlUv3d

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jpa:
    defer-datasource-initialization: false #true
    hibernate:
      ddl-auto: none #create

  sql:
    init:
      mode: always

  level:
    org.hibernate:
      SQL: debug
      type: trace
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

---
spring:
  config:
    activate:
      on-profile: beta

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false #true

logging:
  level:
    org.hibernate:
      SQL: error

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        show_sql: false

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false #true

server:
  port: 8080

logging:
  level:
    org.hibernate:
      SQL: error

notify:
  discord-webhook:
    url: https://discord.com/api/webhooks/1207310185216081960/kMoNygVLXY-0Gth4gz1LP8Nobkt9aa50z0CENUCHKw9jDEFNZmJXev8VVYwUzibfbRmQ