spring:
  application:
    name: ast

  profiles:
    group:
      local: openapi
      prod: openapi
      beta: openapi
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

logging:
  config: classpath:log4j2/log4j2-${spring.profiles.active}.xml

notify:
  discord-webhook:
    url: https://discord.com/api/webhooks/1327825023863357512/6LjBWHyWk69CTbzzXBXRXvM92kfnx369pwzvLB7af01qfhUH6enHsaXfZ5fKc5v1J9xD

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jpa:
    defer-datasource-initialization: false #true
    hibernate:
      ddl-auto: none #create
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

  level:
    org.hibernate:
      SQL: debug
      type: trace
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

---
spring:
  config:
    activate:
      on-profile: beta

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false #true

logging:
  level:
    org.hibernate:
      SQL: error

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        show_sql: false

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false #true

server:
  port: 8080

logging:
  level:
    org.hibernate:
      SQL: error

notify:
  discord-webhook:
    url: https://discord.com/api/webhooks/1327824987930755082/0c2okKWAOgOT8bm9Eo1aF7HrB2AmmKSm4wxqdlegGDa8dnHwCGekatrPDdJQ9prS4LLq