my:
  comprehensive-accountnumber: ${COMPREHENSIVE_ACCOUNTNUMBER}
  accountnumber-product-code: ${ACCOUNTNUMBER_PRODUCT_CODE}

---
spring:
  config:
    activate:
      on-profile: local

openapi:
  rest:
    domain: https://openapivts.koreainvestment.com:29443
    header:
      transaction-id:
        buy-order: VTTC0802U
        sell-order: VTTC0801U
        buy-possible-cash-find: VTTC8908R
    appkey: ${APP_KEY}
    appsecret: ${APP_SECRET}

  websocket:
    domain: ws://ops.koreainvestment.com:31000

---
spring:
  config:
    activate:
      on-profile: prod

openapi:
  rest:
    domain: https://openapivts.koreainvestment.com:9443
    header:
      transaction-id:
        buy-order: TTTC0802U
        sell-order: TTTC0801U
        buy-possible-cash-find: TTTC8908R
      appkey: ${APP_KEY}
      appSecret: ${APP_SECRET}
  websocket:
    domain: ws://ops.koreainvestment.com:21000
