spring:
  application:
    name: ast

  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
logging:
  config: classpath:log4j2/log4j2-${spring.profiles.active}.xml

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jpa:
    defer-datasource-initialization: false #true
    hibernate:
      ddl-auto: none #create


  level:
    org.hibernate:
      SQL: debug
      type: trace
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false #true

logging:
  level:
    org.hibernate:
      SQL: error
